name = "studio-bipelak-automation"
main = "src/index.js"
compatibility_date = "2026-08-01"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "kirkhar"
database_id = "6eddd167-0af2-4ce5-a961-ce8f8af8e233"
migrations_dir = "migrations"
