INSERT OR IGNORE INTO permissions VALUES ('dashboard.view','dashboard.view','مشاهده داشبورد');
INSERT OR IGNORE INTO permissions VALUES ('users.view','users.view','مشاهده کارمندان');
INSERT OR IGNORE INTO permissions VALUES ('users.create','users.create','افزودن کارمند');
INSERT OR IGNORE INTO permissions VALUES ('users.edit','users.edit','ویرایش کارمند');
INSERT OR IGNORE INTO permissions VALUES ('users.permissions','users.permissions','مدیریت دسترسی کارمند');
INSERT OR IGNORE INTO permissions VALUES ('clients.view','clients.view','مشاهده مشتریان');
INSERT OR IGNORE INTO permissions VALUES ('clients.create','clients.create','افزودن مشتری');
INSERT OR IGNORE INTO permissions VALUES ('clients.edit','clients.edit','ویرایش مشتری');
INSERT OR IGNORE INTO permissions VALUES ('clients.delete','clients.delete','حذف مشتری');
INSERT OR IGNORE INTO permissions VALUES ('projects.view','projects.view','مشاهده پروژه‌ها');
INSERT OR IGNORE INTO permissions VALUES ('projects.create','projects.create','ساخت پروژه');
INSERT OR IGNORE INTO permissions VALUES ('projects.edit','projects.edit','ویرایش پروژه');
INSERT OR IGNORE INTO permissions VALUES ('tasks.view','tasks.view','مشاهده تسک‌ها');
INSERT OR IGNORE INTO permissions VALUES ('tasks.create','tasks.create','ساخت تسک');
INSERT OR IGNORE INTO permissions VALUES ('tasks.edit','tasks.edit','ویرایش تسک');
INSERT OR IGNORE INTO permissions VALUES ('hr.view','hr.view','مشاهده منابع انسانی');
INSERT OR IGNORE INTO permissions VALUES ('hr.edit','hr.edit','مدیریت منابع انسانی');
INSERT OR IGNORE INTO permissions VALUES ('freelancers.view','freelancers.view','مشاهده فریلنسرها');
INSERT OR IGNORE INTO permissions VALUES ('freelancers.create','freelancers.create','افزودن فریلنسر');
INSERT OR IGNORE INTO permissions VALUES ('freelancers.edit','freelancers.edit','ویرایش فریلنسر');
INSERT OR IGNORE INTO permissions VALUES ('legal.view','legal.view','مشاهده حقوقی');
INSERT OR IGNORE INTO permissions VALUES ('legal.edit','legal.edit','مدیریت حقوقی');
INSERT OR IGNORE INTO permissions VALUES ('finance.view','finance.view','مشاهده مالی');
INSERT OR IGNORE INTO permissions VALUES ('finance.edit','finance.edit','مدیریت مالی');
INSERT OR IGNORE INTO permissions VALUES ('requests.view','requests.view','مشاهده درخواست‌ها');
INSERT OR IGNORE INTO permissions VALUES ('requests.create','requests.create','ثبت درخواست');
INSERT OR IGNORE INTO permissions VALUES ('requests.approve','requests.approve','تایید درخواست');
INSERT OR IGNORE INTO permissions VALUES ('chat.access','chat.access','ارتباط داخلی');
INSERT OR IGNORE INTO permissions VALUES ('reports.view','reports.view','مشاهده گزارش‌ها');
INSERT OR IGNORE INTO role_permissions SELECT 'Super Admin', id FROM permissions;
INSERT OR IGNORE INTO role_permissions SELECT 'Operations Manager', id FROM permissions;
INSERT OR IGNORE INTO role_permissions SELECT 'Project Manager', id FROM permissions WHERE key IN ('dashboard.view','clients.view','clients.create','clients.edit','projects.view','projects.create','projects.edit','tasks.view','tasks.create','tasks.edit','freelancers.view','requests.view','requests.approve','chat.access','reports.view');
INSERT OR IGNORE INTO role_permissions SELECT 'Employee', id FROM permissions WHERE key IN ('dashboard.view','projects.view','tasks.view','tasks.edit','requests.view','requests.create','chat.access');
INSERT OR IGNORE INTO role_permissions SELECT 'Freelancer', id FROM permissions WHERE key IN ('dashboard.view','projects.view','tasks.view','tasks.edit','requests.create','chat.access');
