import { useEffect, useMemo, useState } from "react";
import { api } from "../api";

const blank = { title:"", description:"", meeting_date:"", start_time:"", end_time:"", timezone:"Asia/Baku", location:"", meeting_link:"", agenda:"", notes:"", status:"Scheduled", project_id:"", attendees:"" };
const dateLabel = value => value ? new Date(value+"T00:00:00").toLocaleDateString("fa-IR") : "—";
export default function Meetings(){
 const [items,setItems]=useState([]),[projects,setProjects]=useState([]),[form,setForm]=useState(blank),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState("");
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function load(){try{const [m,p]=await Promise.all([api("/meetings"),api("/projects")]);setItems(m.items||[]);setProjects(p.items||[]);setError("")}catch(e){setError(e.message||"خطا در دریافت جلسات")}}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>items.filter(x=>(x.title||"").toLowerCase().includes(query.toLowerCase())||(x.location||"").toLowerCase().includes(query.toLowerCase())),[items,query]);
 async function submit(e){e.preventDefault();setError("");if(!form.title.trim()||!form.meeting_date||!form.start_time){setError("عنوان، تاریخ و ساعت شروع الزامی است.");return}if(form.end_time&&form.end_time<=form.start_time){setError("ساعت پایان باید بعد از ساعت شروع باشد.");return}setBusy(true);try{await api("/meetings",{method:"POST",body:JSON.stringify({...form,title:form.title.trim(),project_id:form.project_id||null,attendees:JSON.stringify(form.attendees.split(",").map(v=>v.trim()).filter(Boolean))})});setOpen(false);setForm(blank);await load()}catch(e){setError(e.message||"ثبت جلسه ناموفق بود")}finally{setBusy(false)}}
 async function status(item,value){try{await api("/meetings/"+item.id,{method:"PUT",body:JSON.stringify({status:value})});await load()}catch(e){setError(e.message)}}
 return <section><div className="page-head"><div><small>برنامه‌ریزی و هماهنگی</small><h1>جلسات</h1></div><button className="primary" onClick={()=>setOpen(true)}>+ جلسه جدید</button></div>{error&&<div className="error" role="alert">{error}</div>}<div className="page-head"><input aria-label="جستجوی جلسات" placeholder="جستجو بر اساس عنوان یا مکان" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="cards-list">{filtered.map(x=><article className="list-card" key={x.id}><div><b>{x.title}</b><p>{dateLabel(x.meeting_date)} · {x.start_time}{x.end_time?" تا "+x.end_time:""} · {x.location||"بدون مکان"}</p><p>{x.description||x.agenda||"بدون توضیحات"}</p>{x.meeting_link&&<a href={x.meeting_link} target="_blank" rel="noreferrer">لینک جلسه</a>}</div><div><span className="badge">{x.status}</span><select aria-label="تغییر وضعیت جلسه" value={x.status} onChange={e=>status(x,e.target.value)}><option value="Scheduled">برنامه‌ریزی‌شده</option><option value="In Progress">در حال برگزاری</option><option value="Completed">برگزارشده</option><option value="Cancelled">لغوشده</option></select></div></article>)}{!filtered.length&&<div className="empty">جلسه‌ای برای نمایش نیست.</div>}</div>{open&&<div className="modal"><form className="modal-card" onSubmit={submit}><div className="modal-head"><h2>برنامه‌ریزی جلسه</h2><button type="button" onClick={()=>setOpen(false)} aria-label="بستن">×</button></div><label>عنوان<input required value={form.title} onChange={e=>set("title",e.target.value)}/></label><div className="form-grid"><label>تاریخ<input required type="date" value={form.meeting_date} onChange={e=>set("meeting_date",e.target.value)}/></label><label>شروع<input required type="time" value={form.start_time} onChange={e=>set("start_time",e.target.value)}/></label><label>پایان<input type="time" value={form.end_time} onChange={e=>set("end_time",e.target.value)}/></label><label>منطقه زمانی<input value={form.timezone} onChange={e=>set("timezone",e.target.value)}/></label><label>پروژه<select value={form.project_id} onChange={e=>set("project_id",e.target.value)}><option value="">بدون پروژه</option>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>مکان<input value={form.location} onChange={e=>set("location",e.target.value)}/></label></div><label>لینک آنلاین<input type="url" placeholder="https://..." value={form.meeting_link} onChange={e=>set("meeting_link",e.target.value)}/></label><label>شرکت‌کنندگان (با کاما جدا کنید)<input value={form.attendees} onChange={e=>set("attendees",e.target.value)}/></label><label>دستور جلسه<textarea value={form.agenda} onChange={e=>set("agenda",e.target.value)}/></label><label>توضیحات<textarea value={form.description} onChange={e=>set("description",e.target.value)}/></label><button className="primary" disabled={busy}>{busy?"در حال ثبت...":"ثبت جلسه"}</button></form></div>}</section>
}