const json = (data, status=200) => new Response(JSON.stringify(data), {status, headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const id = () => crypto.randomUUID();
const enc = new TextEncoder();
const hex = b => [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha256(v){ return hex(await crypto.subtle.digest('SHA-256', enc.encode(v))); }
async function readBody(req){ try{return await req.json()}catch{return {}} }
function cookie(req,name){ const m=(req.headers.get('cookie')||'').match(new RegExp('(?:^|; )'+name+'=([^;]+)')); return m?decodeURIComponent(m[1]):null; }
function token(req){ return cookie(req,'bp_session') || (req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'') || null; }
const ROLE_ALL = new Set(['Super Admin','Operations Manager']);
const map={users:'users',clients:'clients',projects:'projects',tasks:'tasks',freelancers:'freelancers',attendance:'attendance',evaluations:'evaluations',contracts:'contracts',finances:'finances',invoices:'invoices',requests:'requests',leave_requests:'leave_requests',conversations:'conversations',messages:'messages'};
const perm={users:'users',clients:'clients',projects:'projects',tasks:'tasks',freelancers:'freelancers',attendance:'hr',evaluations:'hr',contracts:'legal',finances:'finance',invoices:'finance',requests:'requests',conversations:'chat',messages:'chat'};
async function auth(req,env){ const t=token(req); if(!t) return null; const h=await sha256(t); return (await env.DB.prepare(`SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.status='Active'`).bind(h,new Date().toISOString()).first())||null; }
async function permissions(env,user){ if(!user) return []; if(ROLE_ALL.has(user.role)) return (await env.DB.prepare('SELECT key FROM permissions').all()).results.map(x=>x.key); const role=(await env.DB.prepare('SELECT p.key FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE rp.role=?').bind(user.role).all()).results.map(x=>x.key); const overrides=(await env.DB.prepare('SELECT p.key,up.allowed FROM user_permissions up JOIN permissions p ON p.id=up.permission_id WHERE up.user_id=?').bind(user.id).all()).results; const set=new Set(role); for(const x of overrides){if(x.allowed)set.add(x.key);else set.delete(x.key)} return [...set]; }
function requirePerm(user,ps,need){ return user && (ROLE_ALL.has(user.role)||ps.includes(need)); }
async function log(env,user,action,type,entity,description=''){await env.DB.prepare('INSERT INTO activity_logs(id,user_id,action,entity_type,entity_id,description) VALUES(?,?,?,?,?,?)').bind(id(),user?.id||null,action,type,entity,description).run()}
function sqlSafeUpdate(body,allowed){ const fields=Object.keys(body).filter(k=>allowed.has(k)); return fields; }
const fields={users:new Set(['full_name','email','phone','role','department','job_title','employment_type','start_date','salary','status']),clients:new Set(['company_name','contact_person','phone','email','website','instagram','industry','company_size','status','score','notes']),projects:new Set(['title','client_id','manager_id','description','budget','start_date','deadline','priority','status','progress']),tasks:new Set(['title','project_id','assigned_to','priority','status','deadline','description']),freelancers:new Set(['name','specialty','phone','email','city','portfolio','rate','equipment','experience','availability','status','notes']),attendance:new Set(['user_id','date','check_in','check_out','type','notes']),evaluations:new Set(['user_id','month','quality','speed','responsibility','teamwork','notes','evaluated_by']),contracts:new Set(['type','title','client_id','freelancer_id','employee_id','project_id','contract_number','start_date','end_date','amount','status','file_url','notes']),finances:new Set(['type','category','amount','project_id','client_id','freelancer_id','description','date']),invoices:new Set(['invoice_number','client_id','project_id','amount','paid_amount','due_date','status']),requests:new Set(['type','title','description','priority','status','assigned_to','manager_reply']),leave_requests:new Set(['leave_type','start_date','end_date','days','reason','status','approved_by'])};
async function dashboard(env){ const q=async(sql,...b)=>Number((await env.DB.prepare(sql).bind(...b).first())?.n||0); const revenue=await q("SELECT COALESCE(SUM(amount),0) n FROM finances WHERE type='income' AND substr(date,1,7)=substr(date('now'),1,7)"); const expense=await q("SELECT COALESCE(SUM(amount),0) n FROM finances WHERE type='expense' AND substr(date,1,7)=substr(date('now'),1,7)"); const active=await q("SELECT COUNT(*) n FROM projects WHERE status NOT IN ('Completed','Cancelled')"); const overdue=await q("SELECT COUNT(*) n FROM projects WHERE deadline < date('now') AND status NOT IN ('Completed','Cancelled')"); const newClients=await q("SELECT COUNT(*) n FROM clients WHERE substr(created_at,1,7)=substr(date('now'),1,7)"); const pending=await q("SELECT COUNT(*) n FROM clients WHERE status IN ('New Lead','Contacted','Proposal Sent','Negotiation')"); const debt=await q("SELECT COALESCE(SUM(amount-paid_amount),0) n FROM invoices WHERE status!='Paid'"); const upcoming=await q("SELECT COALESCE(SUM(amount-paid_amount),0) n FROM invoices WHERE due_date BETWEEN date('now') AND date('now','+14 day') AND status!='Paid'"); return {monthlyRevenue:revenue,activeProjects:active,overdueProjects:overdue,newClients,pendingClients:pending,monthlyExpenses:expense,netProfit:revenue-expense,customerDebt:debt,upcomingPayments:upcoming}; }
async function handle(req,env){
 const u=new URL(req.url), path=u.pathname.replace(/^\/api\/?/,'').replace(/\/$/,''), method=req.method;
 if(path==='health') return json({ok:true,time:new Date().toISOString()});
 if(path==='auth/login' && method==='POST'){const b=await readBody(req); if(!b.username||!b.password)return json({error:'نام کاربری و رمز عبور الزامی است'},400); const user=await env.DB.prepare('SELECT * FROM users WHERE username=?').bind(b.username).first(); if(!user||user.status!=='Active'||(await sha256(b.password))!==user.password_hash)return json({error:'نام کاربری یا رمز عبور نادرست است'},401); const raw=crypto.randomUUID()+crypto.randomUUID(), hash=await sha256(raw), expires=new Date(Date.now()+1000*60*60*24*7).toISOString(); await env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,?)').bind(id(),user.id,hash,expires).run(); const ps=await permissions(env,user); const r=json({user:{...user,password_hash:undefined,permissions:ps}}); r.headers.set('set-cookie',`bp_session=${encodeURIComponent(raw)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`); return r; }
 if(path==='auth/logout'){const t=token(req);if(t)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(t)).run();const r=json({ok:true});r.headers.set('set-cookie','bp_session=; Path=/; Max-Age=0');return r;}
 const user=await auth(req,env); const ps=await permissions(env,user);
 if(path==='auth/me'){if(!user)return json({user:null},401);return json({user:{...user,password_hash:undefined,permissions:ps}})}
 if(!user)return json({error:'احراز هویت لازم است'},401);
 if(path==='dashboard/stats'){if(!requirePerm(user,ps,'dashboard.view'))return json({error:'دسترسی غیرمجاز'},403);return json({stats:await dashboard(env)})}
 if(path==='permissions'){if(!requirePerm(user,ps,'users.permissions'))return json({error:'دسترسی غیرمجاز'},403);return json({permissions:(await env.DB.prepare('SELECT * FROM permissions ORDER BY key').all()).results})}
 if(path.startsWith('users/') && path.endsWith('/permissions')){if(!requirePerm(user,ps,'users.permissions'))return json({error:'دسترسی غیرمجاز'},403);const uid=path.split('/')[1]; if(method==='GET'){const all=(await env.DB.prepare('SELECT p.id,p.key,p.label,COALESCE(up.allowed,CASE WHEN rp.permission_id IS NOT NULL THEN 1 ELSE 0 END) allowed FROM permissions p LEFT JOIN role_permissions rp ON rp.permission_id=p.id AND rp.role=(SELECT role FROM users WHERE id=?) LEFT JOIN user_permissions up ON up.permission_id=p.id AND up.user_id=? ORDER BY p.key').bind(uid,uid).all()).results;return json({permissions:all})} const b=await readBody(req); await env.DB.prepare('DELETE FROM user_permissions WHERE user_id=?').bind(uid).run(); for(const x of b.permissions||[])await env.DB.prepare('INSERT INTO user_permissions(user_id,permission_id,allowed) VALUES(?,?,?)').bind(uid,x.id,x.allowed?1:0).run(); return json({ok:true}); }
 if(path==='users' && method==='POST'){if(!requirePerm(user,ps,'users.create'))return json({error:'دسترسی غیرمجاز'},403);const b=await readBody(req);if(!b.username||!b.password||!b.full_name)return json({error:'username/password/full_name الزامی است'},400);const uid=id();await env.DB.prepare('INSERT INTO users(id,username,password_hash,full_name,email,phone,role,department,job_title,employment_type,start_date,salary,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(uid,b.username,await sha256(b.password),b.full_name,b.email||null,b.phone||null,b.role||'Employee',b.department||null,b.job_title||null,b.employment_type||null,b.start_date||null,Number(b.salary||0),b.status||'Active').run();await log(env,user,'create','user',uid,b.full_name);return json({id:uid},201)}
 const [resource, rid] = path.split('/'); if(map[resource]){const table=map[resource], needed=(perm[resource]||resource)+'.view'; if(!requirePerm(user,ps,needed))return json({error:'دسترسی غیرمجاز'},403); if(method==='GET' && !rid){let sql=`SELECT * FROM ${table}`;const params=[];const search=u.searchParams.get('q');if(search && ['users','clients','projects','tasks','freelancers','requests'].includes(resource)){const col={users:'full_name',clients:'company_name',projects:'title',tasks:'title',freelancers:'name',requests:'title'}[resource];sql+=` WHERE ${col} LIKE ?`;params.push('%'+search+'%')}sql+=' ORDER BY created_at DESC LIMIT 500';return json({items:(await env.DB.prepare(sql).bind(...params).all()).results})}
 if(method==='GET'&&rid){const item=await env.DB.prepare(`SELECT * FROM ${table} WHERE id=?`).bind(rid).first();return item?json({item}):json({error:'یافت نشد'},404)}
 if(method==='POST'){const need=(perm[resource]||resource)+'.create';if(!requirePerm(user,ps,need))return json({error:'دسترسی غیرمجاز'},403);const b=await readBody(req);if(!fields[resource])return json({error:'منبع نامعتبر'},400);if(resource==='requests')b.user_id=user.id;if(resource==='leave_requests')b.user_id=user.id;if(resource==='conversations')b.created_by=user.id;if(resource==='messages')b.sender_id=user.id;const f=sqlSafeUpdate(b,fields[resource]);const extras=[];if(resource==='requests')extras.push(['ticket_number','REQ-'+Date.now()]);if(resource==='conversations')extras.push(['created_at',new Date().toISOString()]);if(resource==='messages')extras.push(['created_at',new Date().toISOString()]);if(resource==='leave_requests')extras.push(['created_at',new Date().toISOString()]);for(const [k,v] of extras){if(!f.includes(k)){f.push(k);b[k]=v}}if(resource==='requests'&&!f.includes('user_id')){f.push('user_id');b.user_id=user.id}if(resource==='leave_requests'&&!f.includes('user_id')){f.push('user_id');b.user_id=user.id}if(resource==='conversations'&&!f.includes('created_by')){f.push('created_by');b.created_by=user.id}if(resource==='messages'&&!f.includes('sender_id')){f.push('sender_id');b.sender_id=user.id}if(resource==='messages'&&!f.includes('conversation_id'))f.push('conversation_id');if(!f.length)return json({error:'داده‌ای برای ثبت نیست'},400);const rid2=id();const vals=f.map(k=>b[k]??null);const placeholders=f.map(()=>'?').join(',');await env.DB.prepare(`INSERT INTO ${table}(id,${f.join(',')}) VALUES(?,${placeholders})`).bind(rid2,...vals).run();await log(env,user,'create',resource,rid2);return json({id:rid2},201)}
 if(method==='PUT'&&rid){const need=(perm[resource]||resource)+'.edit';if(!requirePerm(user,ps,need))return json({error:'دسترسی غیرمجاز'},403);const b=await readBody(req);const f=sqlSafeUpdate(b,fields[resource]);if(!f.length)return json({error:'داده‌ای برای ویرایش نیست'},400);const set=f.map(k=>`${k}=?`).join(',');await env.DB.prepare(`UPDATE ${table} SET ${set},updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(...f.map(k=>b[k]),rid).run();await log(env,user,'update',resource,rid);return json({ok:true})}
 if(method==='DELETE'&&rid){const need=(perm[resource]||resource)+'.delete';if(!requirePerm(user,ps,need))return json({error:'دسترسی غیرمجاز'},403);await env.DB.prepare(`DELETE FROM ${table} WHERE id=?`).bind(rid).run();await log(env,user,'delete',resource,rid);return json({ok:true})}}
 if(resource==='client-communications'){if(!requirePerm(user,ps,'clients.view'))return json({error:'دسترسی غیرمجاز'},403);const cid=rid;return json({items:(await env.DB.prepare('SELECT * FROM client_communications WHERE client_id=? ORDER BY communication_date DESC').bind(cid).all()).results})}
 if(path.startsWith('client-communications/')){if(!requirePerm(user,ps,'clients.view'))return json({error:'دسترسی غیرمجاز'},403);const cid=path.split('/')[1];if(method==='GET')return json({items:(await env.DB.prepare('SELECT * FROM client_communications WHERE client_id=? ORDER BY communication_date DESC').bind(cid).all()).results});if(method==='POST'){if(!requirePerm(user,ps,'clients.edit'))return json({error:'دسترسی غیرمجاز'},403);const b=await readBody(req);await env.DB.prepare('INSERT INTO client_communications(id,client_id,type,subject,content,created_by) VALUES(?,?,?,?,?,?)').bind(id(),cid,b.type||'note',b.subject||'',b.content||'',user.id).run();return json({ok:true},201)}}
 if(path==='requests/mine'){return json({items:(await env.DB.prepare('SELECT * FROM requests WHERE user_id=? ORDER BY created_at DESC').bind(user.id).all()).results})}
 if(path==='reports/summary'){if(!requirePerm(user,ps,'reports.view'))return json({error:'دسترسی غیرمجاز'},403);return json({stats:await dashboard(env),projects:(await env.DB.prepare('SELECT p.*,c.company_name FROM projects p LEFT JOIN clients c ON c.id=p.client_id ORDER BY p.deadline').all()).results})}
 return json({error:'مسیر پیدا نشد'},404);
}
export default {async fetch(req,env,ctx){try{const u=new URL(req.url);if(u.pathname.startsWith('/api/'))return handle(req,env);const res=await env.ASSETS.fetch(req);return res.status===404?env.ASSETS.fetch(new Request(new URL('/index.html',req.url),req)):res}catch(e){return json({error:e.message||'خطای سرور'},500)}}};
