const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...extra}});
const uid=()=>crypto.randomUUID();
const enc=new TextEncoder();
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
async function sha256(v){return hex(await crypto.subtle.digest('SHA-256',enc.encode(v)))}
async function body(req){try{return await req.json()}catch{return {}}}
function token(req){const c=req.headers.get('cookie')||'';const m=c.match(/(?:^|; )bp_session=([^;]+)/);return m?decodeURIComponent(m[1]):(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'')||null}
async function tableExists(env,t){try{return !!(await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=?").bind(t).first())}catch{return false}}
async function cols(env,t){try{return new Set((await env.DB.prepare(`PRAGMA table_info(${t})`).all()).results.map(x=>x.name))}catch{return new Set()}}
async function auth(req,env){const t=token(req);if(!t)return null;if(!(await tableExists(env,'sessions')))return null;try{return await env.DB.prepare(`SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.status='Active'`).bind(await sha256(t),new Date().toISOString()).first()}catch{return null}}
const RESOURCE={
 users:{table:'users',label:'کارمندان',perm:'employees',search:'full_name'},clients:{table:'clients',label:'مشتریان',perm:'clients',search:'company_name'},projects:{table:'projects',label:'پروژه‌ها',perm:'projects',search:'title'},tasks:{table:'tasks',label:'تسک‌ها',perm:'tasks',search:'title'},freelancers:{table:'freelancers',label:'فریلنسرها',perm:'freelancers',search:'name'},attendance:{table:'attendance',label:'حضور و غیاب',perm:'hr',search:'date'},evaluations:{table:'evaluations',label:'ارزیابی‌ها',perm:'hr',search:'month'},contracts:{table:'contracts',label:'قراردادها',perm:'legal',search:'title'},finances:{table:'finances',label:'مالی',perm:'finance',search:'description'},invoices:{table:'invoices',label:'فاکتورها',perm:'finance',search:'invoice_number'},requests:{table:'requests',label:'درخواست‌ها',perm:'requests',search:'title'},leave_requests:{table:'leave_requests',label:'مرخصی',perm:'hr',search:'reason'},conversations:{table:'conversations',label:'گفتگوها',perm:'chat',search:'title'},messages:{table:'messages',label:'پیام‌ها',perm:'chat',search:'message'}
};
const ALL=new Set(['Super Admin','Operations Manager']);
const allowed={users:['username','full_name','email','phone','role','position','department','job_title','employment_type','start_date','salary','status','permissions','employee_code','notes'],clients:['company_name','contact_person','phone','email','website','instagram','industry','company_size','status','score','notes'],projects:['title','client_id','manager_id','description','budget','start_date','deadline','priority','status','progress'],tasks:['title','project_id','assigned_to','priority','status','deadline','description'],freelancers:['name','specialty','phone','email','city','portfolio','rate','equipment','experience','availability','status','notes'],attendance:['user_id','date','check_in','check_out','type','notes'],evaluations:['user_id','month','quality','speed','responsibility','teamwork','notes','evaluated_by'],contracts:['type','title','client_id','freelancer_id','employee_id','project_id','contract_number','start_date','end_date','amount','status','file_url','notes'],finances:['type','category','amount','project_id','client_id','freelancer_id','description','date'],invoices:['invoice_number','client_id','project_id','amount','paid_amount','due_date','status'],requests:['type','title','description','priority','status','assigned_to','manager_reply'],leave_requests:['user_id','leave_type','start_date','end_date','days','reason','status','approved_by'],conversations:['type','title','project_id','created_by'],messages:['conversation_id','sender_id','message']};
async function permissions(env,u){if(!u)return[];if(ALL.has(u.role))return ['dashboard','employees','clients','projects','tasks','freelancers','hr','legal','finance','requests','chat','reports','users.permissions'];let p=[];try{if(await tableExists(env,'permissions')){p=(await env.DB.prepare('SELECT p.key FROM role_permissions rp JOIN permissions p ON p.id=rp.permission_id WHERE rp.role=?').bind(u.role).all()).results.map(x=>x.key);if(await tableExists(env,'user_permissions')){for(const x of (await env.DB.prepare('SELECT p.key,up.allowed FROM user_permissions up JOIN permissions p ON p.id=up.permission_id WHERE up.user_id=?').bind(u.id).all()).results){if(x.allowed)p.push(x.key);else p=p.filter(k=>k!==x.key)}}}}catch{};try{if(u.permissions){const x=JSON.parse(u.permissions);p.push(...(Array.isArray(x)?x:Object.keys(x).filter(k=>x[k])))} }catch{}return [...new Set(p)]}
function can(u,p,need){return !!u&&(ALL.has(u.role)||p.includes(need)||p.includes(`${need}.view`)||p.includes(p===need?need:`${need}.all`))}
async function log(env,u,action,type,eid){try{if(await tableExists(env,'activity_logs'))await env.DB.prepare('INSERT INTO activity_logs(id,user_id,action,entity_type,entity_id) VALUES(?,?,?,?,?)').bind(uid(),u?.id||null,action,type,eid||null).run()}catch{}}
async function dashboard(env){const q=async(sql)=>Number((await env.DB.prepare(sql).first())?.n||0);const out={};const safe=async(k,sql)=>{try{out[k]=await q(sql)}catch{out[k]=0}};await safe('monthlyRevenue',"SELECT COALESCE(SUM(amount),0)n FROM finances WHERE type IN ('income','revenue') AND substr(date,1,7)=substr(date('now'),1,7)");await safe('monthlyExpenses',"SELECT COALESCE(SUM(amount),0)n FROM finances WHERE type='expense' AND substr(date,1,7)=substr(date('now'),1,7)");await safe('activeProjects',"SELECT COUNT(*)n FROM projects WHERE status NOT IN ('Completed','Cancelled','تکمیل شده','لغو شده')");await safe('overdueProjects',"SELECT COUNT(*)n FROM projects WHERE deadline < date('now') AND status NOT IN ('Completed','Cancelled','تکمیل شده','لغو شده')");await safe('newClients',"SELECT COUNT(*)n FROM clients WHERE substr(created_at,1,7)=substr(date('now'),1,7)");await safe('pendingClients',"SELECT COUNT(*)n FROM clients WHERE status IN ('New Lead','Contacted','Proposal Sent','Negotiation','لید جدید','تماس گرفته شده','جلسه برگزار شده','پیشنهاد ارسال شده','مذاکره')");await safe('customerDebt',"SELECT COALESCE(SUM(amount-paid_amount),0)n FROM invoices WHERE status!='Paid'");await safe('upcomingPayments',"SELECT COALESCE(SUM(amount-paid_amount),0)n FROM invoices WHERE due_date BETWEEN date('now') AND date('now','+14 day') AND status!='Paid'");out.netProfit=(out.monthlyRevenue||0)-(out.monthlyExpenses||0);return out}
async function create(env,u,r,b){
    const t=RESOURCE[r].table;
    const c=await cols(env,t);

if(r==='users' && c.has('permissions') && b.permissions===undefined){
  b.permissions='[]';
}

const keys=(allowed[r]||[]).filter(
  k=>c.has(k)&&b[k]!==undefined
);

if(r==='users'){if(c.has('username')&&!b.username)return json({error:'نام کاربری الزامی است'},400);if(c.has('password_hash')){keys.push('password_hash');b.password_hash=await sha256(b.password||'')}if(c.has('permissions')&&b.permissions===undefined){b.permissions=JSON.stringify([])}if(c.has('position')&&!b.position&&b.job_title)b.position=b.job_title;if(c.has('employment_date')&&!b.employment_date&&b.start_date)b.employment_date=b.start_date;}
if(r==='requests'&&c.has('user_id')){keys.push('user_id');b.user_id=u.id}if(r==='leave_requests'&&c.has('user_id')&&!b.user_id){keys.push('user_id');b.user_id=u.id}if(r==='conversations'&&c.has('created_by')){keys.push('created_by');b.created_by=u.id}if(r==='messages'&&c.has('sender_id')){keys.push('sender_id');b.sender_id=u.id}
const idv=uid();if(c.has('id')){keys.unshift('id');b.id=idv}if(c.has('created_at')&&!keys.includes('created_at')){keys.push('created_at');b.created_at=new Date().toISOString()}if(!keys.length)return json({error:'هیچ فیلد قابل ثبت نیست'},400);const ph=keys.map(()=>'?').join(',');try{await env.DB.prepare(`INSERT INTO ${t}(${keys.join(',')}) VALUES(${ph})`).bind(...keys.map(k=>b[k]??null)).run();await log(env,u,'create',r,idv);return json({ok:true,id:idv},201)}catch(e){return json({error:e.message||'ثبت انجام نشد'},400)}}
async function update(env,u,r,idv,b){const t=RESOURCE[r].table,c=await cols(env,t),keys=(allowed[r]||[]).filter(k=>c.has(k)&&b[k]!==undefined);if(c.has('updated_at'))keys.push('updated_at');if(!keys.length)return json({error:'داده‌ای برای ویرایش نیست'},400);const set=keys.map(k=>`${k}=?`).join(',');const vals=keys.map(k=>k==='updated_at'?new Date().toISOString():b[k]);try{await env.DB.prepare(`UPDATE ${t} SET ${set} WHERE id=?`).bind(...vals,idv).run();await log(env,u,'update',r,idv);return json({ok:true})}catch(e){return json({error:e.message||'ویرایش انجام نشد'},400)}}
async function handle(req,env){const url=new URL(req.url),path=url.pathname.replace(/^\/api\/?/,'').replace(/\/$/,''),method=req.method;
if(path==='health')return json({ok:true});
if(path==='auth/login'&&method==='POST'){const b=await body(req);if(!b.username||!b.password)return json({error:'نام کاربری و رمز عبور الزامی است'},400);const u=await env.DB.prepare('SELECT * FROM users WHERE username=?').bind(b.username).first();if(!u||u.status!=='Active'||await sha256(b.password)!==u.password_hash)return json({error:'نام کاربری یا رمز عبور نادرست است'},401);const raw=uid()+uid(),hash=await sha256(raw),expires=new Date(Date.now()+604800000).toISOString();if(!(await tableExists(env,'sessions')))return json({error:'جدول sessions وجود ندارد؛ migration اولیه را اجرا کنید'},500);await env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,?)').bind(uid(),u.id,hash,expires).run();const ps=await permissions(env,u);return json({user:{...u,password_hash:undefined,permissions:ps}},{headers:{'set-cookie':`bp_session=${encodeURIComponent(raw)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`}})}
const u=await auth(req,env);if(path==='auth/me'){return u?json({user:{...u,password_hash:undefined,permissions:await permissions(env,u)}}):json({user:null},401)}if(path==='auth/logout'){const t=token(req);if(t&&await tableExists(env,'sessions'))await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(t)).run();return json({ok:true},{headers:{'set-cookie':'bp_session=; Path=/; Max-Age=0'}})}if(!u)return json({error:'احراز هویت لازم است'},401);const ps=await permissions(env,u);
if(path==='dashboard/stats')return json({stats:await dashboard(env)});
if(path==='permissions')return can(u,ps,'users.permissions')?json({permissions:(await env.DB.prepare('SELECT * FROM permissions ORDER BY key').all()).results}):json({error:'دسترسی غیرمجاز'},403);
if(path==='requests/mine')return json({items:(await env.DB.prepare('SELECT * FROM requests WHERE user_id=? ORDER BY created_at DESC').bind(u.id).all()).results});
if(path.startsWith('users/')&&path.endsWith('/permissions')){if(!can(u,ps,'users.permissions'))return json({error:'دسترسی غیرمجاز'},403);const idv=path.split('/')[1];if(method==='GET'){try{return json({permissions:(await env.DB.prepare('SELECT p.id,p.key,p.label,COALESCE(up.allowed,CASE WHEN rp.permission_id IS NOT NULL THEN 1 ELSE 0 END) allowed FROM permissions p LEFT JOIN role_permissions rp ON rp.permission_id=p.id AND rp.role=(SELECT role FROM users WHERE id=?) LEFT JOIN user_permissions up ON up.permission_id=p.id AND up.user_id=? ORDER BY p.key').bind(idv,idv).all()).results})}catch{return json({permissions:[]})}}const b=await body(req);try{await env.DB.prepare('DELETE FROM user_permissions WHERE user_id=?').bind(idv).run();for(const x of b.permissions||[])await env.DB.prepare('INSERT INTO user_permissions(user_id,permission_id,allowed) VALUES(?,?,?)').bind(idv,x.id,x.allowed?1:0).run();return json({ok:true})}catch(e){return json({error:e.message},400)}}
if(path.startsWith('client-communications/')){const cid=path.split('/')[1];if(method==='GET')return json({items:(await env.DB.prepare('SELECT * FROM client_communications WHERE client_id=? ORDER BY communication_date DESC').bind(cid).all()).results});if(method==='POST'){const b=await body(req);try{await env.DB.prepare('INSERT INTO client_communications(id,client_id,type,subject,content,created_by) VALUES(?,?,?,?,?,?)').bind(uid(),cid,b.type||'note',b.subject||'',b.content||'',u.id).run();return json({ok:true},201)}catch(e){return json({error:e.message},400)}}}
const [r,idv]=path.split('/');if(RESOURCE[r]){const cfg=RESOURCE[r],need=cfg.perm;if(!can(u,ps,need)&&r!=='requests')return json({error:'دسترسی غیرمجاز'},403);if(method==='GET'&&!idv){let sql=`SELECT * FROM ${cfg.table}`,params=[];const q=url.searchParams.get('q');const c=await cols(env,cfg.table);if(q&&cfg.search&&c.has(cfg.search)){sql+=` WHERE ${cfg.search} LIKE ?`;params.push('%'+q+'%')}if(c.has('created_at'))sql+=' ORDER BY created_at DESC';sql+=' LIMIT 500';try{return json({items:(await env.DB.prepare(sql).bind(...params).all()).results})}catch(e){return json({error:e.message},400)}}if(method==='GET'&&idv){try{const item=await env.DB.prepare(`SELECT * FROM ${cfg.table} WHERE id=?`).bind(idv).first();return item?json({item}):json({error:'یافت نشد'},404)}catch(e){return json({error:e.message},400)}}if(method==='POST'){if(!can(u,ps,need))return json({error:'دسترسی غیرمجاز'},403);return create(env,u,r,await body(req))}if(method==='PUT'&&idv){if(!can(u,ps,need))return json({error:'دسترسی غیرمجاز'},403);return update(env,u,r,idv,await body(req))}if(method==='DELETE'&&idv){if(!can(u,ps,need))return json({error:'دسترسی غیرمجاز'},403);try{await env.DB.prepare(`DELETE FROM ${cfg.table} WHERE id=?`).bind(idv).run();await log(env,u,'delete',r,idv);return json({ok:true})}catch(e){return json({error:e.message},400)}}}
if(path==='reports/summary')return json({stats:await dashboard(env)});return json({error:'مسیر پیدا نشد'},404)}
export default {async fetch(req,env){try{const url=new URL(req.url);if(url.pathname.startsWith('/api/'))return handle(req,env);const asset=await env.ASSETS.fetch(req);return asset.status===404?env.ASSETS.fetch(new Request(new URL('/index.html',req.url),req)):asset}catch(e){return json({error:e.message||'خطای سرور'},500)}}};
